GestorLibrosEntityAjax/Controllers/ClienteController.cs
using GestorLibrosEntityAjax.Filtro;
using GestorLibrosEntityAjax.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorLibrosEntityAjax.Controllers
{
    public class ClienteController : Controller
    {
        Entities contexto = new Entities();

        [FiltroUser]
        public ActionResult verFacturas()

        {
            tusuario usuario = (Session["usuario"] as tusuario);


            return View(usuario.tfactura.ToList<tfactura>());
        }
        [FiltroUser]
        public ActionResult detalleFactura(int CodFactura)
        {

            List<LineaVenta> listaVentas = new List<LineaVenta>();

            foreach (tlineafactura lineaFactura in contexto.tlineafactura.Where(e => e.CodFactura == CodFactura).ToList())
            {
                listaVentas.Add(new LineaVenta(lineaFactura.tlibro, Int32.Parse(lineaFactura.Cantidad)));
            }

            return View(listaVentas);
        }

    }
}

GestorLibrosEntityAjax/Controllers/LibroController.cs
using GestorLibrosEntityAjax.Comun;
using GestorLibrosEntityAjax.Filtro;
using GestorLibrosEntityAjax.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorLibrosEntityAjax.Controllers
{
    public class LibroController : Controller
    {
        Entities contexto = new Entities();

        public ActionResult Consultar()
        {
            return View(contexto.tlibro.Where(e => e.Borrado == "0").ToList());
        }


        public ActionResult verLibro(string CodLibro)
        {
            return View(contexto.tlibro.Find(int.Parse(CodLibro)));
        }

        // Creamos el metodo addLibro que manda a la vista una lista de objetos genericos, en este caso necesitamos la lista de temas-
        [FiltroAdmin]
        public ActionResult addLibro()
        {   //Obtenemos la lisa de temas
            return View(contexto.ttema.ToList());
        }

        //Aqui repetimos el mismo metodo, pero le entra un Libro.
        //Esto es una anotacion, dice que es un metodo post. 
        [FiltroAdmin]
        [HttpPost]
        public ActionResult addLibro(tlibro libro)
        {
            //Se crea una transaccion

            DbContextTransaction transaccion = contexto.Database.BeginTransaction();
            //Hacemos la operaciones necesarias para guardar el nuevo libro.


            libro.Precio = libro.Precio.Replace(".", ",");
            //   libro.CodLibro = UtilFichero.GenerarCodigo(libro.GetType());
            libro.Borrado = "0";
            libro.Formatouno = libro.Formatouno == null ? "N/A" : libro.Formatouno;
            libro.Formatodos = libro.Formatodos == null ? "N/A" : libro.Formatodos;
            libro.Formatotres = libro.Formatotres == null ? "N/A" : libro.Formatotres;

            contexto.tlibro.Add(libro);



            if (contexto.SaveChanges() == 1)
            {
                transaccion.Commit();
                return Content(Mensaje.mostrarmensaje("Libro insertado correctamente", "addLibro"));
            }
            else
            {
                transaccion.Dispose();
                return Content(Mensaje.mostrarmensaje("Error en la transccion...", "addLibro"));

            }
        }

        /*
         *Seguidamente vamos a crear el metodo modificarLibro, aqui.. Hay un problema necesitamos mandarle a la vista 2 modelos, como? Pues un array. 
         * 
         */
        [FiltroAdmin]
        public ActionResult modificarLibro(string codLibro)
        {
            //Creamos el array de objet de 2 posiciones, en el guardaremos el libro y la lista de Temas.
            object[] modelos = new object[2];
            //Obtenermos el libro en a editar en concreto.
            modelos[0] = contexto.tlibro.Find(int.Parse(codLibro));
            //Obtenemos los tipos de libros
            modelos[1] = contexto.ttema.ToList<ttema>();
            //Devolvemos el array a la lista.
            return View(modelos);
        }

        [FiltroAdmin]
        [HttpPost]
        public ActionResult modificarLibro(tlibro libro)
        {

            DbContextTransaction transaccion = contexto.Database.BeginTransaction();
            //   contexto.tlibro.Find(libro.CodLibro).IDTema = libro.IDTema;
            contexto.tlibro.Find(libro.CodLibro).Precio = libro.Precio.Replace(".", ",");
            contexto.tlibro.Find(libro.CodLibro).Borrado = "0";
            contexto.tlibro.Find(libro.CodLibro).Formatouno = libro.Formatouno == null ? "N/A" : libro.Formatouno;
            contexto.tlibro.Find(libro.CodLibro).Formatodos = libro.Formatodos == null ? "N/A" : libro.Formatodos;
            contexto.tlibro.Find(libro.CodLibro).Formatotres = libro.Formatotres == null ? "N/A" : libro.Formatotres;



            if (contexto.SaveChanges() == 1)
            {
                transaccion.Commit();
                return RedirectToAction("Consultar");
            }
            else
            {
                transaccion.Dispose();
                return Content(Mensaje.mostrarmensaje("Error", "Consultar"));

            }
        }

        //  return RedirectToAction("Inicio");


        [FiltroAdmin]
        public ActionResult borrarLibro(string CodLibro)
        {

            DbContextTransaction transaccion = contexto.Database.BeginTransaction();

            contexto.tlibro.Find(CodLibro).Borrado = "1";

            if (contexto.SaveChanges() == 1)
            {
                transaccion.Commit();
                return RedirectToAction("Consultar");
            }
            else
            {
                transaccion.Dispose();
                return Content(Mensaje.mostrarmensaje("erroe", "modificarLibro"));

            }


        }

        public ActionResult addCarrito(string CodLibro, string accion)
        {


            Carrito carrito = Session["carro"] as Carrito;
            carrito.AddItem(contexto.tlibro.Find(int.Parse(CodLibro)));
            /*
             * Estas dos lineas se pueden unificar en una : 
             *(Session["carro"] as Carrito).AddItem((control.Buscar(new TLibro().GetType(), CodLibro)) as TLibro); 
             */

            return RedirectToAction("Consultar");
        }


        public ActionResult borrarItemCarrito(string CodLibro)
        {
            (Session["carro"] as Carrito).RemoveItem(contexto.tlibro.Find(int.Parse(CodLibro)));

            return RedirectToAction("Consultar");

        }

    }

}

GestorLibrosEntityAjax/Views/Plantilla/Plantilla.cshtml
@using GestorLibrosEntityAjax.Controllers
@using GestorLibrosEntityAjax.Models

<!DOCTYPE html>
<html lang="en">
<head>
    @*.:IES ARROYO HARNINA:.*@
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="css/footer.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="~/Content/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <a class="navbar-brand" href="/">IES ARROYO HARNINA</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">


                    @{
                        if (Session["usuario"] == null)
                        {
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Login <span class="caret"></span></a>
                                <ul id="login-dp" class="dropdown-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form class="form" role="form" method="post" action="/Inicio/login" accept-charset="UTF-8" id="login-nav">
                                                    <div class="form-group">
                                                        <label class="sr-only" for="exampleInputEmail2">Usuario</label>
                                                        <input name="Nick" type="text" class="form-control" id="exampleInputEmail2" placeholder="Introduce Usuario" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="sr-only" for="exampleInputPassword2">Contraseña</label>
                                                        <input name="Pass" type="password" class="form-control" id="exampleInputPassword2" placeholder="Introduce Contraseña" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-primary btn-block">Loguearse</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>


                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Registrarse <span class="caret"></span></a>
                                <ul id="login-dp" class="dropdown-menu">
                                    <li>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <form class="form" role="form" method="post" action="/Inicio/Registro" accept-charset="UTF-8" id="login-nav">
                                                    <div class="form-group">
                                                        <label class="sr-only" for="exampleInputEmail2">Usuario</label>
                                                        <input name="Nick" type="text" class="form-control" id="exampleInputEmail2" placeholder="Introduce Usuario" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <label class="sr-only" for="exampleInputPassword2">Contraseña</label>
                                                        <input name="Pass" type="password" class="form-control" id="exampleInputPassword2" placeholder="Introduce Contraseña" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>


                        }
                    }

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Trabajar Con Libros</a>
                        <div class="dropdown-menu">
                            <div class="dropdown-item">@Html.ActionLink("Consultar", "Consultar", "Libro")</div>

                            @{
                                if (Session["usuario"] != null && ((tusuario)Session["usuario"]).Rol.Equals("admin"))
                                {
                                    <div class="dropdown-item">@Html.ActionLink("Añadir Libro", "addLibro", "Libro")</div>
                                }

                            }

                        </div>
                    </li>

                    @{
                        if (Session["usuario"] != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Perfil</a>
                                <div class="dropdown-menu">
                                    <div class="dropdown-item">@Html.ActionLink("Ver Facturas", "verFacturas", "Cliente")</div>
                                </div>
                            </li>
                        }
                    }



                    <!--


                       // int? aux = (Session["carro"] as List<LibreriaV3._1.Modelo.TLibro>)?.Count;
                       // int encarro = aux ?? 0;

                    <div>
                        <a href="//Url.Action("Consultar", "Libro")"><img src="~/Content/Imagen/img.png" /></a>
                        <span class="badge badge-pill badge-info cart-badge">//encarro</span>
                    </div>
                      -->





                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Carrito</a>
                        <div class="dropdown-menu">

                            @{
                                if (Session["carro"] != null)
                                {
                                    float total = 0f;
                                    Carrito carrito = (Carrito)Session["carro"];

                                    foreach (var linea in carrito.ItemList)

                                    {
                                        total = total + linea.subTotal();
                                        <div class="dropdown-item">
                                            <span class="item">
                                                <span class="item-left">
                                                    <span class="item-info">
                                                        <span>
                                                            Libro : @linea.Libro.Titulo
                                                        </span>
                                                        <span>
                                                            Cantidad : @linea.Cantidad
                                                        </span>
                                                        <span>
                                                            Precio : @linea.subTotal() €
                                                        </span>
                                                    </span>
                                                </span>
                                                <span class="item-right">
                                                    @Html.ActionLink("+", "addCarrito", "Libro", new { CodLibro = @linea.Libro.CodLibro }, new { @class = "btn btn-xs btn-primary pull-right" })
                                                    @Html.ActionLink("-", "borrarItemCarrito", "Libro", new { CodLibro = @linea.Libro.CodLibro }, new { @class = "btn btn-xs btn-danger pull-right" })

                                                </span>
                                            </span>
                                        </div>
                                    }
                                    <span>Total : @total €</span>
                                }

                            }


                            <form action="/Carrito/carrito" method="post">
                                <button class="btn btn-xs btn-success btn-block">Comprar</button>
                            </form>


                        </div>

                    </li>




                </ul>

                <!--Carritooooo-->





            </div>
        </nav>
    </header>




    @RenderBody()


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>